#!/bin/bash

# Agent Work Merger
# Safely merges optimization work from agent branches back to main

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
ORCHESTRATOR="$SCRIPT_DIR/orchestrator.sh"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m'

log_info() {
    echo -e "${BLUE}[MERGE]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[MERGE]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[MERGE]${NC} $1"
}

log_error() {
    echo -e "${RED}[MERGE]${NC} $1"
}

# Get current branch
current_branch=$(git branch --show-current)
log_info "Current branch: $current_branch"

# Get all active agent branches
log_info "🔍 Discovering active agent branches..."
agent_branches=$(git branch | grep "agent-" | sed 's/^[+ ]*//' || echo "")

if [[ -z "$agent_branches" ]]; then
    log_warning "No agent branches found to merge"
    exit 0
fi

echo ""
log_info "Found agent branches:"
echo "$agent_branches" | while read branch; do
    echo "  • $branch"
done

echo ""
log_info "🔄 Merge Options:"
echo "  1. merge-all     - Merge all agent branches automatically"
echo "  2. merge-select  - Choose specific branches to merge"
echo "  3. preview       - Show what each branch has changed"
echo "  4. status        - Check agent status before merging"

if [[ $# -eq 0 ]]; then
    echo ""
    echo "Usage: $0 <merge-all|merge-select|preview|status>"
    exit 1
fi

command="$1"

case "$command" in
    "status")
        log_info "📊 Checking agent status..."
        "$ORCHESTRATOR" list
        echo ""
        log_info "🌿 Agent branch status:"
        echo "$agent_branches" | while read branch; do
            if [[ -n "$branch" ]]; then
                commits=$(git log --oneline "${current_branch}..${branch}" | wc -l | tr -d ' ')
                if [[ "$commits" -gt 0 ]]; then
                    log_info "  ${branch}: ${commits} new commits"
                    git log --oneline "${current_branch}..${branch}" | head -3 | sed 's/^/    /'
                else
                    log_warning "  ${branch}: no new commits"
                fi
                echo ""
            fi
        done
        ;;
        
    "preview")
        log_info "📋 Preview of agent changes..."
        echo "$agent_branches" | while read branch; do
            if [[ -n "$branch" ]]; then
                echo ""
                log_info "🔍 Changes in $branch:"
                
                commits=$(git log --oneline "${current_branch}..${branch}" | wc -l | tr -d ' ')
                if [[ "$commits" -gt 0 ]]; then
                    echo "  📝 Commits:"
                    git log --oneline "${current_branch}..${branch}" | sed 's/^/    /'
                    
                    echo ""
                    echo "  📄 Changed files:"
                    git diff --name-only "${current_branch}..${branch}" | sed 's/^/    /'
                else
                    log_warning "    No changes in this branch"
                fi
                echo ""
            fi
        done
        ;;
        
    "merge-all")
        log_info "🚀 Starting automatic merge of all agent branches..."
        
        # Ensure we're on the main branch
        cd "$PROJECT_ROOT"
        git checkout "$current_branch"
        
        # Merge each agent branch
        echo "$agent_branches" | while read branch; do
            if [[ -n "$branch" ]]; then
                log_info "🔀 Merging $branch..."
                
                commits=$(git log --oneline "${current_branch}..${branch}" | wc -l | tr -d ' ')
                if [[ "$commits" -gt 0 ]]; then
                    # Create merge commit with descriptive message
                    git merge --no-ff "$branch" -m "feat: Merge agent optimization work from $branch

Auto-merge of agent improvements:
- Agent: $(echo $branch | sed 's/agent-//' | sed 's/-[0-9]*$//')
- Commits: $commits
- Generated by: Agent Work Merger

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
                    
                    log_success "✅ Merged $branch ($commits commits)"
                else
                    log_warning "⏭️  Skipped $branch (no changes)"
                fi
            fi
        done
        
        log_success "🎉 All agent branches merged successfully!"
        log_info "📊 Current status:"
        git log --oneline -5
        ;;
        
    "merge-select")
        log_info "🎯 Interactive branch selection..."
        echo ""
        echo "$agent_branches" | while read branch; do
            if [[ -n "$branch" ]]; then
                commits=$(git log --oneline "${current_branch}..${branch}" | wc -l | tr -d ' ')
                if [[ "$commits" -gt 0 ]]; then
                    echo -e "${GREEN}$branch${NC} (${commits} commits)"
                    git log --oneline "${current_branch}..${branch}" | head -2 | sed 's/^/  /'
                    echo ""
                    read -p "Merge this branch? [y/N]: " -n 1 -r
                    echo ""
                    if [[ $REPLY =~ ^[Yy]$ ]]; then
                        log_info "🔀 Merging $branch..."
                        cd "$PROJECT_ROOT"
                        git merge --no-ff "$branch" -m "feat: Merge selected agent work from $branch"
                        log_success "✅ Merged $branch"
                    else
                        log_info "⏭️  Skipped $branch"
                    fi
                    echo ""
                else
                    log_warning "$branch (no changes)"
                fi
            fi
        done
        ;;
        
    *)
        log_error "Unknown command: $command"
        echo "Available commands: merge-all, merge-select, preview, status"
        exit 1
        ;;
esac

echo ""
log_info "🏁 Merge operation completed"